name: Data Scrapper

on:
  schedule:
    - cron: '0 */3 * * *' # Run every 3 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        category_class: ["human_and_emotions", "nature_and_wildlife", "urban_tech_and_space", "objects_and_fx", "explorer"]
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r data_scrapper/requirements.txt
          # For OpenCV in headless environments
          sudo apt-get update && sudo apt-get install -y libgl1

      - name: Run Scraper (${{ matrix.category_class }})
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO_ID: ${{ secrets.HF_REPO_ID }}
        run: python data_scrapper/src/data_scraper/main.py --category_class "${{ matrix.category_class }}" --items 25
